# Generated by Django 6.0.5 on 2026-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparison',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
