# Generated by Django 6.0.5 on 2026-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comparison_is_archived_comparison_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
